### ISSUE TITLE
make granularities configurable

### ISSUE THREAD

**Issue by Max-Meldrum** [uwheel/uwheel#19]
Look into allowing granularities to be configured.  For instance, by default all granularities are enabled. But if users want more coarse-grained windowing, then the lowest granularity could be changed (e.g., seconds instead of millis, or minutes instead of secs+milli).

The lowest granularity would also decide the ticking unit and the space requirement in the Write-ahead Wheel. For example, if milliseconds is used and assuming 100ms per slot (10 slots per second) then the WAW would require a lot more write-ahead slots.

```toml
[features]
default = ["full"]
full = ["milliseconds", "seconds", "minutes", "hours", "days", "weeks", "years"]
milliseconds = []
seconds = ["milliseconds"]
minutes = ["seconds"]
hours = ["minutes"]
days = ["hours"]
weeks = ["days"]
years = ["weeks"]
```
